NUMBER_OF_OIL_FIELDS = 1000
MIN_VOLUME = 200000
MAX_VOLUME = 150000000
MIN_DRILLING_DEPTH = 100
MAX_DRILLING_DEPTH = 5000

STARTING_CASH = 30000000

DRILL_FACTORY_BASE_PRODUCTION_RATE = 10
DRILL_FACTORY_BASE_UPKEEP_COST = 5000
DRILL_FACTORY_BUILD_COST = 4000000
DRILL_FACTORY_LEVEL_UPKEEP_FACTOR = 1.7
DRILL_FACTORY_LEVEL_PRODUCTION_FACTOR = 2

PUMP_FACTORY_BASE_PRODUCTION_RATE = 3
PUMP_FACTORY_BASE_UPKEEP_COST = 10000
PUMP_FACTORY_BUILD_COST = 14000000
PUMP_FACTORY_LEVEL_UPKEEP_FACTOR = 1.7
PUMP_FACTORY_LEVEL_PRODUCTION_FACTOR = 2

PIPE_FACTORY_BASE_PRODUCTION_RATE = 50
PIPE_FACTORY_BASE_UPKEEP_COST = 6000
PIPE_FACTORY_BUILD_COST = 7000000
PIPE_FACTORY_LEVEL_UPKEEP_FACTOR = 1.7
PIPE_FACTORY_LEVEL_PRODUCTION_FACTOR = 2

WAGON_FACTORY_BASE_PRODUCTION_RATE = 15
WAGON_FACTORY_BASE_UPKEEP_COST = 7000
WAGON_FACTORY_BUILD_COST = 6000000
WAGON_FACTORY_LEVEL_UPKEEP_FACTOR = 1.7
WAGON_FACTORY_LEVEL_PRODUCTION_FACTOR = 2

STORAGE_TANK_FACTORY_BASE_PRODUCTION_RATE = 2
STORAGE_TANK_FACTORY_BASE_UPKEEP_COST = 17000
STORAGE_TANK_FACTORY_BUILD_COST = 15000000
STORAGE_FACTORY_LEVEL_UPKEEP_FACTOR = 1.7
STORAGE_FACTORY_LEVEL_PRODUCTION_FACTOR = 2
